---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trivy-reporter
  name: trivy-reporter
  namespace: trivy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-reporter
  template:
    metadata:
      labels:
        app: trivy-reporter
    spec:
      containers:
      - image: ghcr.io/codingric/trivy-reporter:latest
        name: trivy-reporter
        ports:
        - name: http
          containerPort: 8080
      serviceAccount: trivy-reporter
      serviceAccountName: trivy-reporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: trivy-reporter
  name: trivy-reporter
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - aquasecurity.github.io
  resources:
  - vulnerabilityreports
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: trivy-reporter
  name: trivy-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-reporter
subjects:
- kind: ServiceAccount
  name: trivy-reporter
  namespace: trivy-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: trivy-reporter
  name: trivy-reporter
  namespace: trivy-system